### ISSUE TITLE
[Bug]: net::ERR_HTTP2_PROTOCOL_ERROR 200

### ISSUE THREAD

**Issue by janakkapadia** [qruto/laravel-wave#32]
### What happened?

Cannot connect with wave. error with this net::ERR_HTTP2_PROTOCOL_ERROR 200 on HTTP/2 and net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK) on HTTP/1.1 on console

### How to reproduce the bug

Installation process shown on github repo and see in console

### Package Version

0.7.1

### PHP Version

8.2.8

### Laravel Version

10.15.0

### Which operating systems does with happen with?

macOS, Linux

**Comment by slavarazum** [comment]
Hi!
Try to use the latest version:
```bash
composer update qruto/laravel-wave
```

**Comment by slavarazum** [comment]
@janakkapadia Have you had a chance to try the latest version?

**Comment by slavarazum** [comment]
Feel free to reopen it if you still have an issue on the latest version.
