### ISSUE TITLE
[Bug]: Cors: no 'Access-Control-Allow-Origin' header is present on the requested resource. 

### ISSUE THREAD

**Issue by ezequidias** [qruto/laravel-wave#33]
### What happened?

I use api in laravel!! I add only allowed urls in config/cors.php (allowed_origins)

localhost:8080/wave not use 'Access-Control-Allow-Origin'

### How to reproduce the bug

![Screenshot_select-area_20230731033040](https://github.com/qruto/laravel-wave/assets/25870781/c590143d-cd81-4136-8f33-3baaafe01dc7)
![Screenshot_select-area_20230731033750](https://github.com/qruto/laravel-wave/assets/25870781/9ab4a0de-4bef-474e-a7c3-29053fa002c1)

### Package Version

0.7.1

### PHP Version

8.2.0

### Laravel Version

10.16.1

### Which operating systems does with happen with?

Linux

**Comment by slavarazum** [comment]
Hey 👋 How did you solve it?

**Comment by ezequidias** [comment]
The error was in AWS and google cloud services!! the problem was firewall related! Laravel Wave is working normally, but I'm still doing more tests!

**Comment by slavarazum** [comment]
Got it, thanks! Stay in touch.
