### ISSUE TITLE
[Bug]:  ob_flush(): Failed to flush buffer. No buffer to flush

### ISSUE THREAD

**Issue by edalzell** [qruto/laravel-wave#35]
### What happened?

Running SSE normally (redis worker running, Echo on front end).

See a ton of these in my log: https://flareapp.io/share/87newjDP

### How to reproduce the bug

Run my app.

Sorry don't know the repro issue yet.

### Package Version

0.7.1

### PHP Version

8.2.8

### Laravel Version

10.18.0

### Which operating systems does with happen with?

macOS

**Comment by edalzell** [comment]
This code silences the error, not sure yet if everything still works:

```php
if (ob_get_contents()) {
    ob_flush();
}
```

**Comment by slavarazum** [comment]
Hi @edalzell. Probably you have disabled [output buffering](https://www.php.net/manual/en/outcontrol.configuration.php) on the server.

Is it works normal on a local environment?
Have you debugged what `echo $this` returns at `ServerSentEvent::__invoke` method?

**Comment by edalzell** [comment]
> Hi @edalzell. Probably you have disabled [output buffering](https://www.php.net/manual/en/outcontrol.configuration.php) on the server.
> 
> Is it works normal on a local environment? Have you debugged what `echo $this` returns at `ServerSentEvent::__invoke` method?

This error is occurring locally. And I didn't used to get it, it's a new thing.

**Comment by edalzell** [comment]
But I did switch recently to Herd (from Brew/Valet), so maybe it is off? I'll check, thanks!

**Comment by slavarazum** [comment]
Probably we have found a source, let test it on Herd.

**Comment by edalzell** [comment]
Confirmed, Herd does NOT have `output_buffering = 4096` in its php.ini.

Sorry about the confusing.

**Comment by slavarazum** [comment]
NP, thank you for your involvement.
