### ISSUE TITLE
[Bug]: Unable to prepare route

### ISSUE THREAD

**Issue by ezequidias** [qruto/laravel-wave#48]
### What happened?

when you type the `php artisan optimize` command

### How to reproduce the bug

 `php artisan optimize` 

### Package Version

0.8.0

### PHP Version

8.2.0

### Laravel Version

10.28

### Which operating systems does with happen with?

Linux

### Notes

![Screenshot_38](https://github.com/qruto/laravel-wave/assets/25870781/7ef896d3-3fe9-4016-aaa9-ecea6c28814f)

**Comment by slavarazum** [comment]
Hi @ezequidias!

I have published the route caching issue for the second time 😅 I have added a [test case](https://github.com/qruto/laravel-wave/commit/3e57403da59b284da64603b8e0c2176c4b259122) for it.

You tested it so quickly after the release. Well done! Thank you for staying in touch.

**Comment by ezequidias** [comment]
Yes laravel wave is my favorite package haha! It's very promising! 
Thank you so much for everything !
