### ISSUE TITLE
[Bug]: Octane compatibility does not work!

### ISSUE THREAD

**Issue by ezequidias** [qruto/laravel-wave#49]
### What happened?

I'm trying to connect laravel octane with laravel wave! however, it is repeating the GET requests for /wave in the console!

I'm using laradock + laravel octane + swoole!
pecl -q install swoole-4.8.12

roadrunner the same thing happens too!

### How to reproduce the bug

install laradock + swoole + laravel wave

### Package Version

0.8.0

### PHP Version

8.2.0

### Laravel Version

10.28

### Which operating systems does with happen with?

Linux

### Notes

![Screenshot_39](https://github.com/qruto/laravel-wave/assets/25870781/e1955f69-af0f-4d4c-a33a-eb3d9e9379d2)

**Comment by slavarazum** [comment]
Is it something in application logs?

Tested with Swoole 5.1.1

**Comment by ezequidias** [comment]
I'll do more tests! and install a newer version of swoole !

**Comment by ezequidias** [comment]
Now it is working correctly!
I updated swoole to the latest version! and other packages too! Now it's working perfectly!

Thank you very much !

**Comment by slavarazum** [comment]
Enjoy 😉
