### ISSUE TITLE
[Bug]: Live demo has an expired SSL certificate

### ISSUE THREAD

**Issue by rodrigopedra** [qruto/laravel-wave#54]
### What happened?

Accessing https://wave.qruto.dev/ gives an error as its SSL certificate expired on Feb 7th, 2024

![Screenshot_20240210_153345](https://github.com/qruto/laravel-wave/assets/5470108/15fd7c72-ef3a-41b8-b84d-00b90efe4032)

### How to reproduce the bug

Access https://wave.qruto.dev/ from a browser

### Package Version

0.8.1

### PHP Version

8.2.15

### Laravel Version

10.43.0

### Which operating systems does with happen with?

Linux

### Notes

I wasn't sure how to contact you about this, but thought you'd like to know. Thanks for this package, works like a charm.

**Comment by slavarazum** [comment]
Thanks! updated.

**Comment by angristan** [comment]
👋 It expired again

**Comment by slavarazum** [comment]
Thanks @angristan! updated ✅

**Comment by oliverbj** [comment]
Expired again :)

**Comment by Reddishye** [comment]
@slavarazum Expired again
